### ISSUE TITLE
kenza start panic: exit status 1

### ISSUE THREAD

**Issue by zhangchunsheng** [Kenza-AI/kenza#16]
panic: exit status 1

goroutine 1 [running]:
github.com/kenza-ai/kenza/cli.startCommand(0xd42850, 0x0, 0x0, 0x1, 0x1, 0x18)
        /Users/joakimouli/dev/kenza/kenza/cli/start.go:158 +0x2fb
github.com/kenza-ai/kenza/cli.glob..func7(0xd20160, 0xd42850, 0x0, 0x0)
        /Users/joakimouli/dev/kenza/kenza/cli/start.go:75 +0x149
github.com/spf13/cobra.(*Command).execute(0xd20160, 0xd42850, 0x0, 0x0, 0xd20160, 0xd42850)
        /Users/joakimouli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd1f4e0, 0xc00003c750, 0xc00004df50, 0x40574f)
        /Users/joakimouli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/joakimouli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/kenza-ai/kenza/cli.Execute(...)
        /Users/joakimouli/dev/kenza/kenza/cli/root.go:40
main.main()
        /Users/joakimouli/dev/kenza/kenza/main.go:23 +0x32

sudo docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-96.gitb2f74b2.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      b2f74b2/1.13.1
 Built:           Wed May  1 14:55:20 2019
 OS/Arch:         linux/amd64
 Experimental:    false

Kenza info

Version: v0.0.1-alpha
Built:   2020-05-31T19:11:02Z
Commit:  3f3dc270e9a4a03dd687467c0b058764f7fbb931

**Comment by kirakik** [comment]
Testing gumloop
